ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "colorTags" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "colorAnomalyScore" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "colorAnomalyConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "colorFindings" TEXT NOT NULL DEFAULT '[]';
