ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "diseaseLabel" TEXT;
ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "diseaseConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "diseaseHealthy" BOOLEAN;
ALTER TABLE "PlantPhoto" ADD COLUMN IF NOT EXISTS "diseasePredictions" TEXT NOT NULL DEFAULT '[]';
